#!/bin/sh

set -e
niter=10000

echo === Map a log file into memory mapped file
time ./crlog -i $niter -o /tmp/crlog.raw.map

echo === Write into memory and decode instandly into file
time ./crlog -i $niter --instant-decode > /tmp/crlog.raw.txt

echo === Use fprintf
time ./crlog -m fprintf -i $niter -o /tmp/crlog.fprintf.txt

echo === Use dprintf
time ./crlog -m dprintf -i $niter -o /tmp/crlog.dprintf.txt

echo === Use sprintf
time ./crlog -m sprintf -i $niter

echo === Use fputs
time ./crlog -m fputs -i $niter -o /tmp/crlog.fputs.txt

echo === Use fstream
time ./tests/fstream $niter

echo === Decode binary
time ./crlog -d < /tmp/crlog.raw.map > /tmp/crlog.raw.map.txt

echo === Compare outputs
cmp /tmp/crlog.raw.map.txt /tmp/crlog.fprintf.txt
cmp /tmp/crlog.raw.txt /tmp/crlog.fprintf.txt
cmp /tmp/crlog.dprintf.txt /tmp/crlog.fprintf.txt
cmp /tmp/crlog.fputs.txt /tmp/crlog.fprintf.txt
cmp /tmp/crlog.fstream.txt /tmp/crlog.fprintf.txt
